
CREATE TABLE KhachHang(
    MaKhachHang INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TenKH VARCHAR(50) NOT NULL ,
    SoDT INT(11)
);
CREATE TABLE BenXe(
    MaBen INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TenBen VARCHAR(50) NOT NULL     
);
CREATE TABLE ChuyenDi(
    MaChuyen INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TenChuyen VARCHAR(50) NOT NULL ,
    NgayGio Datetime,
    SoLuongGhe int,
    BenXuatPhat INT(11),
    FOREIGN KEY (BenXuatPhat) REFERENCES BenXe(MaBen)
);
CREATE TABLE NhanVien(
    MaNV INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TenNV VARCHAR(50) NOT NULL ,
    email VARCHAR (50) NOT NULL ,
    ChucVu VARCHAR (50) NOT NULL 
);
CREATE TABLE VeXe(
    MaVe INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GiaTien DOUBLE,
    LoaiVe VARCHAR (50) NOT NULL 
);
CREATE TABLE ChiTietVeXe(
    MaChiTietVe INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MaVeXe INT(11) NOT NULL,
    MaKH INT(11) NOT NULL,
    MaNV INT(11) NOT NULL,
    MaCD INT(11) NOT NULL,
    SoGhe VARCHAR (50) NOT NULL ,
    FOREIGN KEY (MaVeXe) REFERENCES VeXe(MaVe),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKhachHang),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaCD) REFERENCES ChuyenDi(MaChuyen)
);
CREATE TABLE GioKhoiHanh(
    MaTai int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GioDi time
);

ALTER TABLE ChuyenDi ADD FOREIGN KEY(BenXeDen) REFERENCES BenXe(MaBen);

ALTER TABLE ChuyenDi ADD FOREIGN KEY(GioKhoiHanh) REFERENCES GioKhoiHanh(MaTai);

